### PR TITLE
Fix: replaced Files.readString with BufferedReader to avoid OOM (#41)

### LINKED ISSUE #41: OutOfMemoryError in IngestionService.collectRawLogs due to large file read
We're encountering an `OutOfMemoryError` in the scheduled task responsible for ingesting local logs. The error originates from trying to read a file that's too large using `Files.readAllBytes()` / `Files.readString()`.

**Stack Trace:**

```
2025-05-20T10:22:23.872Z ERROR 864 --- [regression] [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.OutOfMemoryError: Required array size too large
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3287)
	at java.base/java.nio.file.Files.readString(Files.java:3359)
	at java.base/java.nio.file.Files.readString(Files.java:3318)
	at com.kenyajug.regression.services.IngestionService.collectRawLogs(IngestionService.java:131)
	at com.kenyajug.regression.services.IngestionService.processLocalLogs(IngestionService.java:72)
	at com.kenyajug.regression.scheduled.LocalLogsIngestionCron.runIngestionJob(LocalLogsIngestionCron.java:39)
	...
```

**Root Cause:**
`Files.readAllBytes()` and `Files.readString()` attempt to load the entire file into memory, which can cause an `OutOfMemoryError` if the file is too large for the available heap.

**Proposed Solution:**
Refactor `collectRawLogs()` to use a streaming approach when reading large files, such as:

* Using a `BufferedReader` and reading line by line.
* Applying a size threshold to skip or stream large files.
* Logging a warning for oversized files.

**Steps to Reproduce:**

1. Place a very large file in the directory being ingested by `IngestionService`.
2. Trigger the ingestion job.
3. Observe the OOM error.

**Environment:**

* App version: `1.0.0`
* Spring Context: `6.2.6`
* JVM: Java 21+
* Scheduler: `@Scheduled` method in `LocalLogsIngestionCron`

### PR DESCRIPTION
**Pull request by LeX1Ka**
Fixes #41
Replaced Files.readString with streaming via BufferedReader in collectRawLogs().
Prevents OutOfMemoryError when reading large log files.

### CODE REVIEW

**Comment by samuelowino** [comment]
@LeX1Ka we need to validate test coverage before merging

Please run:

```bash
mvn verify
```

This will generate the latest test coverage report in project readme. A coverage of **100% is required** for this branch to be eligible for merge.

To identify any missing branches or lines:

1. Open the following file in your browser:

   ```
   /target/site/jacoco/index.html
   ```
2. Review the highlighted sections in the report to locate untested code.

📘 Reference guide for generating and interpreting reports:
👉 https://www.codingshuttle.com/spring-boot-handbook/ja-co-co-test-report-generation/

Once coverage is verified at 100%, commit the updated report and proceed with the merge.

File: src/main/java/com/kenyajug/regression/utils/DateTimeUtils.java [hunk 1]
```diff
@@ -151,15 +152,13 @@ public static String localDateTimeToUTCTime(LocalDateTime localDateTime) {
...
-            return LocalDateTime.from(temporal);
-        } catch (DateTimeParseException formatException){
-            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSX");
-            var temporal = formatter.parse(timestamp);
-            return LocalDateTime.from(temporal);
+            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm:ss.SSS", Locale.ENGLISH);
+            return LocalDateTime.parse(timestamp, formatter);
+        } catch (DateTimeParseException formatException) {
+            DateTimeFormatter fallbackFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSX");
+            return LocalDateTime.parse(timestamp, fallbackFormatter);
```
Comment (samuelowino) [inline src/main/java/com/kenyajug/regression/utils/DateTimeUtils.java:161]: How does this affect the issue this PR is meant to address? Logs loading performance

**Review by samuelowino — CHANGES_REQUESTED** [review]
Don't expand the scope of the PR

File: target/site/jacoco/index.html [hunk 2]
```diff
@@ -0,0 +1 @@
...="bar" id="b8"><img src="jacoco-resources/greenbar.gif" width="1" height="10" title="15" alt="15"/></td><td class="ctr2" id="c8">100 %</td><td class="bar" id="d8"/><td class="ctr2" id="e8">n/a</td><td class="ctr1" id="f8">0</td><td class="ctr2" id="g8">3</td><td class="ctr1" id="h8">0</td><td class="ctr2" id="i6">6</td><td class="ctr1" id="j8">0</td><td class="ctr2" id="k8">3</td><td class="ctr1" id="l8">0</td><td class="ctr2" id="m8">1</td></tr><tr><td id="a3"><a href="com.kenyajug.regression.models/index.html" class="el_package">com.kenyajug.regression.models</a></td><td class="bar" id="b9"><img src="jacoco-resources/greenbar.gif" width="1" height="10" title="12" alt="12"/></td><td class="ctr2" id="c9">100 %</td><td class="bar" id="d9"/><td class="ctr2" id="e9">n/a</td><td class="ctr1" id="f9">0</td><td class="ctr2" id="g9">1</td><td class="ctr1" id="h9">0</td><td class="ctr2" id="i9">1</td><td class="ctr1" id="j9">0</td><td class="ctr2" id="k9">1</td><td class="ctr1" id="l9">0</td><td class="ctr2" id="m9">1</td></tr></tbody></table><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.12.202403310830</span></div></body></html>
```
Comment (samuelowino) [inline target/site/jacoco/index.html:1]: The test coverage is automatically written to the project readme, you should not create this file

Once you run `mvn verify` the readme file should automatically update

Consider deleting this file

**Review by samuelowino — CHANGES_REQUESTED** [review]

**Comment by samuelowino** [comment]
@LeX1Ka this is the test coverage report I'm referring to, you should find it in the project readme

Screenshot 2025-05-20 at 23 08 06

**Comment by samuelowino** [comment]
> I’ve restored the DateTimeUtils file and cleaned up the staged changes as requested. The README.md was also updated and committed.

Your commit is missing restoration of DateTimeUtils file and the removal of the html file. You probably forgot to add them to staged before committing. [cec2f8b](https://github.com/kenya-jug/regression/pull/59/commits/cec2f8bec69d87eb3c03e4009cff132aa0ac5d3c) only contains changes to the README file

**Comment by samuelowino** [comment]
Screenshot 2025-05-20 at 23 53 48

**Comment by LeX1Ka** [comment]
I removed the target/site/jacoco/index.html file from the repository, as it shouldn’t be committed.
Also, I updated the README to reflect this change.

Sorry if I missed something or if anything is still not perfect.
Thank you very much for your help and patience.

**Comment by samuelowino** [comment]
> I removed the target/site/jacoco/index.html file from the repository, as it shouldn’t be committed. Also, I updated the README to reflect this change.
> 
> Sorry if I missed something or if anything is still not perfect. Thank you very much for your help and patience.

Brilliant fixes! The read and index.html are now removed.

The DateTimeUtils.java is still not resolved. 
You can fix this by copy pasting [this version](https://github.com/kenya-jug/regression/blob/main/src/main/java/com/kenyajug/regression/utils/DateTimeUtils.java) to your local DateTimeUtils.java file: https://github.com/kenya-jug/regression/blob/main/src/main/java/com/kenyajug/regression/utils/DateTimeUtils.java
After pasting the main repo version the diff should disappear

This will ensure your PR is clean

**Review by samuelowino — APPROVED** [review]
Looks good to go! Nice work 👍🏿
